#!/bin/bash

# Dependancy List
deps=(
    nvim
    ripgrep
)

# Update
printf "\e[33mUpdating Pacman\e[00m\n"
sudo pacman -Syu --noconfirm
sudo pacman -S --noconfirm --needed --base-devel

# Install deps
printf "\e[33mInstalling ${deps[*]}\e[00m\n"
sudo paru -S --noconfirm ${deps[*]}

# Setup dotfiles
printf "\e[33mLinking nvim config\e[00m\n"
mkdir -pf $HOME/.config/nvim
ln -sf $PWD $HOME/.config/nvim


# Installing Plugins
nvim --headless -c PackerInstall &
sleep 10
sudo pkill nvim

